service: serverless-appsync
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2

plugins:
  - serverless-appsync-plugin

#AppSync   
custom:
  appSync:
    name: youtubeAppSyncApi
    authenticationType: AMAZON_COGNITO_USER_POOLS
    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM
    userPoolConfig:
      awsRegion: us-west-2
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - type: Query
        field: getBookById
        dataSource: booksTable
      - type: Query 
        field: listBooks
        dataSource: booksTable
      - type: Mutation
        field: createBook
        dataSource: booksTable
    dataSources:
      - type: AMAZON_DYNAMODB
        name: booksTable
        config:
          tableName: !Ref booksTable
# Resources     
resources:
  Resources:
    ${file(resources.yml)}



